version: "3.7"

services:
    database_games:
        image: postgres
        container_name: database_games
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=queries_challenge
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: queries_challenge
        ports:
         - 3333:3333
        volumes:
         - .:/user/app
        links:
         - database_games
        depends_on:
         - database_games

volumes:
    pgdata:
        driver: local